# -*- coding: utf-8 -*-
"""ASSIGNMENT 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xq-afToa76J-1oR4OyM4dJwoUHO3VRJY

ASSIGNMENT 1
"""

x=input().split(" ")
y=0.0
for i in x:
  y=y+float(i)
print(y)

"""ASSIGNMENT 2

"""

from IPython.core.display import Javascript

x=input("enter string: ")
l=0
j=[]
for i in set(x):
    k=x.count(i)
    if k>l:
        l=x.count(i)
        j=i
    else:
        continue
print(j)

marks = {
    "Maths" : "80",
    "English" : "41",
    "Hindi" : "95",
    "Science" : "95",
    "Social Science" : "100"
}
max_marks = max(marks,key=marks.get)
print(max_marks)