# -*- coding: utf-8 -*-
"""ASSIGNMENT 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xq-afToa76J-1oR4OyM4dJwoUHO3VRJY

ASSIGNMENT 1
"""

x=input().split(" ")
y=0.0
for i in x:
  y=y+float(i)
print(y)

"""ASSIGNMENT 2

"""

x="nakirekantinandan"
y=input("choose n,a,k,i,r,e,t,d: ")
p=[x[0],x[3],x[5],x[9],x[7]]
if y.lower() in p:
  print("YOU WON")
else:
  print("you lost try again")