# -*- coding: utf-8 -*-
"""sum 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xq-afToa76J-1oR4OyM4dJwoUHO3VRJY
"""

x=input().split(" ")
y=0.0
for i in x:
  y=y+float(i)
print(y)